
#global_frame: /map
#robot_base_frame: /base_link
#transform_tolerance: 0.5
#update_frequency: 5
#publish_frequency: 5

#max_obstacle_height: 0.90  # assume something like an arm is mounted on top of the robot
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.25
footprint: [[0.21, 0.16], [0.21, -0.16], [-0.21, -0.16], [-0.21, 0.16]] 
transform_tolerance: 5
map_type: costmap##??useful??
#origin_z: 0.0
#z_resolution: 0.2
#z_voxels: 2
#publish_voxel_map: false
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
##, expected_update_rate: 5, observation_persistence: 5.0, obstacle_range: 5, raytrace_range: 5
