controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true
## above are new

TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.2
  min_vel_x: 0.05 #0.00

  max_vel_theta: 1.2
  min_vel_theta: -1.2
  min_in_place_vel_theta: 0.1
  
  escape_vel: -0.1
  
  acc_lim_x: 0.25
  acc_lim_theta: 0.25

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3

# Forward Simulation Parameters
  sim_time: 1.0 #5.0
  vx_samples: 10
  #angular_sim_granularity: 0.25
  vtheta_samples: 20 #30

# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.05
  heading_lookahead: 0.325 
   
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.1
  #oscillation_timeout:    0.0

# mechanum robot configuration(unable)
  holonomic_robot: false
  max_vel_y: 0.0#0.2
  min_vel_y: 0.0#0.03
  acc_lim_y: 0.0#0.25
  vy_samples: 0#10
  

