global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 1.0 #1.5
  publish_frequency: 0#1.5
  static_map: true
  rolling_window: false
  #unknown_cost_value: 0
  #publish_voxel_map: false
  #lethal_cost_threshold: 100
  #map_topic: /map
  map_type: costmap
  transform_tolerance: 1.5##new
  resolution: 0.05##new
  #track_unknow_space: false
