#
#                            GLOBAL PLANNER
#
base_global_planner: global_planner/GlobalPlanner

PlannerCore:
   allow_unknown: true
   default_tolerance: 0.0
   visualize_potential: true
   use_dijkstra: false
   use_quadratic: false
   use_grid_path: true
   old_navfn_behavior: false
