local_costmap:
   global_frame: /odom
   robot_base_frame: /base_link
   update_frequency: 15.0
   publish_frequency: 10.0
   static_map: false
   rolling_window: true
   width: 2.0
   height: 2.0
   resolution: 0.025
   transform_tolerance: 0.5

