# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#

 
shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 5.0

planner_frequency: 0  #only run when a new goal is received or the local planner reports that its path is blocked
planner_patience: 5.0

oscillation_distance: 0.2

recovery_behavior_enabled: true
clearing_rotation_allowed: false

